name: Build, Push, Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

  deploy-doks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Substitute variables in deployment.yml
        run: envsubst < .deployment/k8s.yml.template > .deployment/k8s.yml
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          DOMAIN: ${{ secrets.DOMAIN }}
          BOT_LANG: th

      - name: Substitute variables in deployment.yml [EN]
        run: envsubst < .deployment/k8s-en.yml.template > .deployment/k8s-en.yml
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN_EN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET_EN }}
          DOMAIN: ${{ secrets.DOMAIN_EN }}
          BOT_LANG: en

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          kubectl apply -f .deployment/k8s.yml -n ${{ secrets.DIGITALOCEAN_NAMESPACE }}
          kubectl apply -f .deployment/k8s-en.yml -n ${{ secrets.DIGITALOCEAN_NAMESPACE }}
